config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get root to: 'homes#top'
    get 'admin/homes/index/:id',to: 'homes#index'
    resources :items, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    #以下の内容でも
    # resources :customers, only: %i[index show edit update]
  end

  scope module: :customer do
    root to: "homes#top"
    get 'homes/about'
    # resource :customers, only: %i[show edit update] do
    #   collection do
    #     get 'unsubscribe'
    #     patch 'withdrawal'
    #   end
    # end
    get 'customers/unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal', to: 'customers#withdrawal', as: 'withdrawal'
    get 'customers/show', to: 'customers#show'
    get 'customers/edit_information', to: 'customers#edit'
    patch 'customers/update', to: 'customers#update'
    resources :items, only: [:index, :show, :create]
    resources :cart_items, only: %i[index update destroy create] do
      delete 'destroy_all', on: :collection
    end
    resources :shipping_addresses, only: %i[index create edit update destroy]
    resources :orders, only: %i[new index create show] do
      collection do
        get 'check'
        get 'completed'
      end
    end
  end

  resources :genres, only: [:index, :create, :edit, :update ]

end

app/models/customer.rb
class Customer < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  with_options presence: true do 
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :email
    validates :encrypted_password
    validates :postal_code
    validates :address
    validates :telephone_number
  end
  
  validates :postal_code, length: { minimum: 7}
  # nameの文字数制限
  
  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  before_action :authenticate_admin!
  before_action :set_product, only: %i[show edit update]
  
  def index
    @customers = Customer.all
  end

  def show
  end

  def edit
  end
  
  def update
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
      flash[:notice] = "会員情報の編集に成功しました。"
    else
      render :edit
      flash[:notice] = "会員情報の編集に失敗しました。"
    end
  end
  
  
  private
  
  def set_product
    @customer = Customer.find(params[:id])
  end
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  before_action :authenticate_customer!
  before_action :set_params, only: %i[update destroy]

  def index
    @cart_items = current_customer.cart_items.all
    @count = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }  #合計金額の計算
  end

  def create
    # cart_item = CartItem.new(cart_item_params)
    # cart_item.customer_id = current_customer.id
    #省略した形↓↓↓
    cart_item = current_customer.cart_items.new(cart_item_params)
    
    if current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
      cart_item = CartItem.find_by(item_id: params[:cart_item][:item_id])
      cart_item.amount += params[:cart_item][:amount].to_i
      cart_item.update(amount: cart_item.amount)
      redirect_to cart_items_path, notice: "カートへの保存に成功しました。"
    else
      if cart_item.save
          redirect_to cart_items_path, notice: "カートへの保存に成功しました。"
      else
          render :index, notice: "カートへの保存に失敗しました。"
          # render template: "customer/items/show", notice: "カートへの保存に失敗しました。"
          # @cart_item = CartItem.new
          # @item = Item.find(params[:id])
          # render template: "customer/items/show"
      end
    end
  end

  def update
    if @cart_item.update(cart_item_params)
      redirect_to cart_items_path, notice: "数量の変更に成功しました。"
    end
  end

  def destroy
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end

  private


  def set_params
    @cart_item = CartItem.find(params[:id])
  end

  #ストロングパラメータ
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end

end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  
  before_action :authenticate_customer!
  before_action :set_product, only: %i[show edit update unsubscribe withdrawal]

  def show
  end

  def edit
  end
  
  def update
    if @customer.update(customer_params)
      redirect_to customers_show_path, notice: "会員情報の編集に成功しました。"
    else
      flash[:notice] = "会員情報の編集に失敗しました。"
      render  :edit
    end
  end
  
  def unsubscribe
  end
  
  def withdrawal
    @customer.update(is_deleted: true)  #is_deletedカラムをtrueに変更する
    reset_session #セッション情報を全て削除
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end
  
  
  private
  
  def set_product
    @customer = current_customer
  end
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    @items = Item.all
  end

  def about
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  
  before_action :set_params, only: %i[show]
  def index
    @items = Item.all.page(params[:page]).per(8)
  end

  def show
    @cart_item = CartItem.new
  end
  
  
  private
  
  def set_params
    @item = Item.find(params[:id])
  end
  
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  before_action :authenticate_customer!
  before_action :set_params, only: %i[show]

  def new
    @order = Order.new
  end

  def check
    @order = Order.new(order_params)
    @cart_items = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }  #商品合計金額の計算
    if params[:order][:select_address] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.address_name = current_customer.last_name + current_customer.first_name

    elsif params[:order][:select_address] == "1"
      @address = ShippingAddress.find(params[:order][:address_id])
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.address_name = @address.address_name
    elsif params[:order][:select_address] == "2"

    else
      @order = Order.new
      render :new
      flash[:notice] = "再度ご確認の上、ご入力してください。"
    end
    @order.postage = 800
  end

  def completed
  end

  def create
    order = current_customer.orders.new(order_params)
    cart_item = current_customer.cart_items.all
    order.status = 0

    if order.save
      cart_item.each do |cart_item| 
        OrderDetail.create(   #注文詳細モデルのカラムのcreate
          item_id: cart_item.item_id, order_id: order.id,
          quantity: cart_item.amount, price: cart_item.item.price
        )
      end
      cart_item.destroy_all
      redirect_to completed_orders_path
    else
      @order = Order.new
      render :new
      flash[:notice] = "注文の確定に失敗しました。"
    end
    
  end

  def index
    @orders = current_customer.orders.all
    # byebug
  end

  def show
    @orders = current_customer.orders.find(params[:id])
    # @order_detail = current_customer.order_details.all
  end

  private


  def set_params
    @order = Order.find(params[:id])
  end

  def order_params
    # params.require(:order).permit(:payment_method, :postal_code, :address, :address_name)
    params.require(:order).permit(:customer_id, :payment_method, :payment, :postage, :address, :postal_code, :address_name, :status)
  end

end

app/controllers/customer/shipping_addresses_controller.rb
class Customer::ShippingAddressesController < ApplicationController
  
  before_action :authenticate_customer!
  before_action :set_product, only: %i[edit update destroy]

  def index
    @shipping_address = ShippingAddress.new
    @shipping_addresses = current_customer.shipping_addresses
  end

  def create
    @shipping_address = current_customer.shipping_addresses.new(shipping_address_params)
    if @shipping_address.save
      flash[:notice] = "配送先情報の登録に成功しました。"
      redirect_to shipping_addresses_path
    else
      flash[:notice] = "配送先情報の登録に失敗しました。"
      @shipping_address = ShippingAddress.new
      @shipping_addresses = ShippingAddress.all
      render :index
    end
  end

  def edit
  end

  def update
    if @shipping_address.update(shipping_address_params)
      flash[:notice] = "配送先情報の更新に成功しました。"
      redirect_to shipping_addresses_path
    else
      flash[:notice] = "配送先情報の更新に失敗しました。"
      render :edit
    end

  end

  def destroy
    @shipping_address.destroy
    flash[:notice] = "配送先情報の削除に成功しました。"
    redirect_to shipping_addresses_path
  end


  private

  def set_product
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def shipping_address_params
    params.require(:shipping_address).permit(:address, :postal_code, :address_name, :customer_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/shipping_addresses_helper.rb
module Customer::ShippingAddressesHelper
end

app/views/customer/customers/edit.html.erb
<div class="container"> 
  <h1>会員情報編集</h1>
  
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  
  <%= form_with model: @customer, url: customers_update_path, method: :patch, local: true do |f| %>
    <span>名前</span>
    <%= f.label :last_name, "（姓）" %>
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
    <%= f.label :first_name, "（名）" %>
    <%= f.text_field :first_name, autofocus: true %>
    <br>
  
    <span>フリガナ</span>
    <%= f.label :last_name_kana, "（セイ）" %>
    <%= f.text_field :last_name_kana, autofocus: true %>
    <%= f.label :first_name_kana, "（メイ）" %>
    <%= f.text_field :first_name_kana, autofocus: true %>
    <br>
  
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
     <br>
  
    <%= f.label :postal_code, "郵便番号（ハイフンなし）" %>
    <%= f.text_field :postal_code %>
     <br>
  
    <%= f.label :address, "住所" %>
    <%= f.text_field :address %>
    <br>
  
    <%= f.label :telephone_number, "電話番号（ハイフンなし）" %>
    <%= f.telephone_field :telephone_number %>
    <br>
  
    <div class="row">
      <div class="col-lg-3">
        <%= f.submit "変更内容を保存" , class: "btn btn-success"%>
      </div>
      <%= link_to "退会する", unsubscribe_path, class: "btn btn-danger m-1" %>
    </div>
  <% end %>
  
</div>

app/views/customer/customers/show.html.erb
<div class="container">
  <h1>マイページ</h1>
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  <p>登録情報<span><%= link_to " 編集する", customers_edit_information_path %></span></p>
  
  <table class="table table-bordered">
    <tr>
      <th>氏名</th>
      <td><%=@customer.last_name %> <%=@customer.first_name %></td>
    </tr>
    
    <tr>
      <th>カナ</th>
      <td><%=@customer.last_name_kana %> <%=@customer.first_name_kana %></td>
    </tr>
    
    <tr>
      <th>郵便番号</th>
      <td><%=@customer.postal_code %></td>
    </tr>
    
    <tr>
      <th>住所</th>
      <td><%=@customer.address %></td>
    </tr>
    
    <tr>
      <th>電話番号</th>
      <td><%=@customer.telephone_number %></td>
    </tr>
    
    <tr>
      <th>メールアドレス</th>
      <td><%=@customer.email %></td>
    </tr>
    
  </table>
  
  <span>配送先 <%= link_to "一覧を見る", shipping_addresses_path %><span>
  <br>
  <span>注文詳細 <%= link_to "一覧を見る", orders_path %></span>
</div>

app/views/customer/customers/unsubscribe.html.erb
<div class="container">
  <h2>本当に退会しますか？</h2>
  <p>
    退会すると、会員登録情報や<br>
    これまでの購入履歴が閲覧できなくなります<br>
    退会する場合は、「退会する」をクリックしてください。
  </p>

  <span><%= link_to '退会しない', customers_show_path, class: "btn btn-success" %></span>
  <span><%= link_to '退会する', withdrawal_path, method: :patch, class: "btn btn-danger" %></span>
</div>