config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get root to: 'homes#top'
    get 'admin/homes/index/:id',to: 'homes#index'
    resources :items, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    #以下の内容でも
    # resources :customers, only: %i[index show edit update]
  end

  scope module: :customer do
    root to: "homes#top"
    get 'homes/about'
    # resource :customers, only: %i[show edit update] do
    #   collection do
    #     get 'unsubscribe'
    #     patch 'withdrawal'
    #   end
    # end
    get 'customers/unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal', to: 'customers#withdrawal', as: 'withdrawal'
    get 'customers/show', to: 'customers#show'
    get 'customers/edit_information', to: 'customers#edit'
    patch 'customers/update', to: 'customers#update'
    resources :items, only: [:index, :show, :create]
    resources :cart_items, only: %i[index update destroy create] do
      delete 'destroy_all', on: :collection
    end
    resources :shipping_addresses, only: %i[index create edit update destroy]
    resources :orders, only: %i[new index create show] do
      collection do
        get 'check'
        get 'completed'
      end
    end
  end

  resources :genres, only: [:index, :create, :edit, :update ]

end

app/models/customer.rb
class Customer < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  with_options presence: true do 
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :email
    validates :encrypted_password
    validates :postal_code
    validates :address
    validates :telephone_number
  end
  
  validates :postal_code, length: { minimum: 7}
  # nameの文字数制限
  
  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
end

app/models/order.rb
class Order < ApplicationRecord

  with_options presence: true do
    validates :payment_method
    validates :payment
    validates :postage
    validates :address
    validates :postal_code
    validates :address_name
    validates :status
  end
  
  #購入方法
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  #注文ステータス
  enum status: {
    
    waiting_payment: 0,      #入金待ち
    payment_confirmation: 1, #入金確認
    production: 2,           #製作中
    shipping_preparation: 3, #発送準備中
    sent: 4                  #発送済み
    
  }

  # with_options uniqueness: true do
  # end
  
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  def address_display
  '〒' + postal_code + ' ' + address
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  before_action :authenticate_admin!
  before_action :set_product, only: %i[show edit update]
  
  def index
    @customers = Customer.all
  end

  def show
  end

  def edit
  end
  
  def update
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
      flash[:notice] = "会員情報の編集に成功しました。"
    else
      render :edit
      flash[:notice] = "会員情報の編集に失敗しました。"
    end
  end
  
  
  private
  
  def set_product
    @customer = Customer.find(params[:id])
  end
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    if order.update(order_params)
      redirect_to admin_order_path(order.id)
      flash[:notice] = "注文商品の更新に成功しました。"
    else
      flash[:notice] = "注文商品の更新に失敗しました。"
      render :show
    end
    
    order.order_details.update(production_status: 1) if order.status == "payment_confirmation"
  end
  
  private
  
  def order_params
    params.require(:order).permit(:customer_id, :payment_method, :payment, :postage, :address, :postal_code, :address_name, :status)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  before_action :authenticate_customer!
  before_action :set_params, only: %i[update destroy]

  def index
    @cart_items = current_customer.cart_items.all
    @count = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }  #合計金額の計算
  end

  def create
    # cart_item = CartItem.new(cart_item_params)
    # cart_item.customer_id = current_customer.id
    #省略した形↓↓↓
    cart_item = current_customer.cart_items.new(cart_item_params)
    
    if current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
      cart_item = CartItem.find_by(item_id: params[:cart_item][:item_id])
      cart_item.amount += params[:cart_item][:amount].to_i
      cart_item.update(amount: cart_item.amount)
      redirect_to cart_items_path, notice: "カートへの保存に成功しました。"
    else
      if cart_item.save
          redirect_to cart_items_path, notice: "カートへの保存に成功しました。"
      else
          render :index, notice: "カートへの保存に失敗しました。"
          # render template: "customer/items/show", notice: "カートへの保存に失敗しました。"
          # @cart_item = CartItem.new
          # @item = Item.find(params[:id])
          # render template: "customer/items/show"
      end
    end
  end

  def update
    if @cart_item.update(cart_item_params)
      redirect_to cart_items_path, notice: "数量の変更に成功しました。"
    end
  end

  def destroy
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end

  private


  def set_params
    @cart_item = CartItem.find(params[:id])
  end

  #ストロングパラメータ
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end

end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  
  before_action :authenticate_customer!
  before_action :set_product, only: %i[show edit update unsubscribe withdrawal]

  def show
  end

  def edit
  end
  
  def update
    if @customer.update(customer_params)
      redirect_to customers_show_path, notice: "会員情報の編集に成功しました。"
    else
      flash[:notice] = "会員情報の編集に失敗しました。"
      render  :edit
    end
  end
  
  def unsubscribe
  end
  
  def withdrawal
    @customer.update(is_deleted: true)  #is_deletedカラムをtrueに変更する
    reset_session #セッション情報を全て削除
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end
  
  
  private
  
  def set_product
    @customer = current_customer
  end
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    @items = Item.all
  end

  def about
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  
  before_action :set_params, only: %i[show]
  def index
    @items = Item.all.page(params[:page]).per(8)
  end

  def show
    @cart_item = CartItem.new
  end
  
  
  private
  
  def set_params
    @item = Item.find(params[:id])
  end
  
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  before_action :authenticate_customer!
  before_action :set_params, only: %i[show]

  def new
    @order = Order.new
  end

  def check
    @order = Order.new(order_params)
    @cart_items = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }  #商品合計金額の計算
    if params[:order][:select_address] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.address_name = current_customer.last_name + current_customer.first_name

    elsif params[:order][:select_address] == "1"
      @address = ShippingAddress.find(params[:order][:address_id])
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.address_name = @address.address_name
    elsif params[:order][:select_address] == "2"

    else
      @order = Order.new
      render :new
      flash[:notice] = "再度ご確認の上、ご入力してください。"
    end
    @order.postage = 800
  end

  def completed
  end

  def create
    order = current_customer.orders.new(order_params)
    cart_item = current_customer.cart_items.all
    order.status = 0

    if order.save
      cart_item.each do |cart_item| 
        OrderDetail.create(   #注文詳細モデルのカラムのcreate
          item_id: cart_item.item_id, order_id: order.id,
          quantity: cart_item.amount, price: cart_item.item.price
        )
      end
      cart_item.destroy_all
      redirect_to completed_orders_path
    else
      @order = Order.new
      render :new
      flash[:notice] = "注文の確定に失敗しました。"
    end
    
  end

  def index
    @orders = current_customer.orders.all
    # byebug
  end

  def show
    @orders = current_customer.orders.find(params[:id])
    # @order_detail = current_customer.order_details.all
  end

  private


  def set_params
    @order = Order.find(params[:id])
  end

  def order_params
    # params.require(:order).permit(:payment_method, :postal_code, :address, :address_name)
    params.require(:order).permit(:customer_id, :payment_method, :payment, :postage, :address, :postal_code, :address_name, :status)
  end

end

app/controllers/customer/shipping_addresses_controller.rb
class Customer::ShippingAddressesController < ApplicationController
  
  before_action :authenticate_customer!
  before_action :set_product, only: %i[edit update destroy]

  def index
    @shipping_address = ShippingAddress.new
    @shipping_addresses = current_customer.shipping_addresses
  end

  def create
    @shipping_address = current_customer.shipping_addresses.new(shipping_address_params)
    if @shipping_address.save
      flash[:notice] = "配送先情報の登録に成功しました。"
      redirect_to shipping_addresses_path
    else
      flash[:notice] = "配送先情報の登録に失敗しました。"
      @shipping_address = ShippingAddress.new
      @shipping_addresses = ShippingAddress.all
      render :index
    end
  end

  def edit
  end

  def update
    if @shipping_address.update(shipping_address_params)
      flash[:notice] = "配送先情報の更新に成功しました。"
      redirect_to shipping_addresses_path
    else
      flash[:notice] = "配送先情報の更新に失敗しました。"
      render :edit
    end

  end

  def destroy
    @shipping_address.destroy
    flash[:notice] = "配送先情報の削除に成功しました。"
    redirect_to shipping_addresses_path
  end


  private

  def set_product
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def shipping_address_params
    params.require(:shipping_address).permit(:address, :postal_code, :address_name, :customer_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/shipping_addresses_helper.rb
module Customer::ShippingAddressesHelper
end

app/views/customer/orders/check.html.erb
<div class="container">
  <h1>注文情報確認</h1>

  <%= form_with model: @order, url: orders_path, method: :post do |f| %>
    <div class="row">

      <div class="col">
        <table class="table table-bordered">

          <thead>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
          </thead>
          
          <tbody>
            <% @cart_items.each do |cart_item| %>
            <tr>
              <td>
                <%= image_tag cart_item.item.image, size: "50x50" %>
                <%= cart_item.item.name %>
              </td>
              <td><%= cart_item.item.with_tax_price.to_s(:delimited) %></td>
              <td><%= cart_item.amount %></td>
              <!--小計の計算-->
              <td><%= (cart_item.item.with_tax_price * cart_item.amount).to_s(:delimited) %></td>
            </tr>
            <% end %>
          </tbody>

        </table>
      </div>

      <div class="col">
        <table class="table table-bordered">
          <tr>
            <td>送料</td>
            <td><%= @order.postage %>円</td>
            <%= f.hidden_field :postage, :value => @order.postage %>
          </tr>
          <tr>
            <td>商品合計</td>
            <td><%= @total.to_s(:delimited) %>円</td>
            <%= f.hidden_field :payment, :value => @total %>
          </tr>
          <tr>
            <td>請求金額</td>
            <td><%= (@total + @order.postage).to_s(:delimited) %>円</td>
          </tr>
        </table>
      </div>
    </div>

    <div class="row">
      <p>支払い方法</p>
      <%= @order.payment_method_i18n %>
      <%= f.hidden_field :payment_method, :value => @order.payment_method %>
    </div>

    <div class="row">
      <p>お届け先</p>
      <%= @order.address_display %>
      <%= f.hidden_field :address, :value => @order.address %>
      <%= f.hidden_field :postal_code, :value => @order.postal_code %>
      <%= f.hidden_field :address_name, :value => @order.address_name %>
      <br>
      <%= @order.address_name %>
    </div>
    <%= f.submit "注文を確定する" %>
  <% end %>
</div>

app/views/customer/orders/completed.html.erb
<div class="container">
  <h2>ご注文ありがとうございます！</h2>
</div>

app/views/customer/orders/index.html.erb
<div class="container">
  <h2>注文履歴一覧</h2>

  <table class="table table-bordered">
    <thead>
      <th>注文日</th>
      <th>配送先</th>
      <th>注文商品</th>
      <th>支払金額</th>
      <th>ステータス</th>
      <th>注文詳細</th>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
          <td>
            〒<%= order.postal_code %>
            <br>
            <%= order.address %>
            <br>
            <%= order.address_name %>
          </td>
          <td>
            <% order.order_details.each do |order_detail| %>
              <%= order_detail.item.name %><br>
            <% end %>
          </td>
          <td><%= order.payment + order.postage %></td>
          <td><%= order.status_i18n %></td>
          <td><%= link_to "表示する", order_path(order.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customer/orders/new.html.erb
<div class="container">
  
  <h1>注文情報入力</h1>
  
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  
  <%= form_with model: @order, url: check_orders_path, method: :GET do |f| %>
  
    <p>支払い方法</p>
    <%= f.radio_button :payment_method, Order.payment_methods.key(0) %>
    <%= f.label :payment_method_credit_card, Order.payment_methods_i18n[:credit_card] %>
    <br>
    <%= f.radio_button :payment_method, Order.payment_methods.key(1) %>
    <%= f.label :payment_method_transfer, Order.payment_methods_i18n[:transfer] %>

    <p>お届け先</p>
    <%= f.radio_button :select_address, 0 %>
    <%= f.label :select_address_0, "ご自身の住所" %>
    <br>
    〒<%= current_customer.postal_code %>
    <!--郵便番号-->
    <%= current_customer.address %><br>
    <!--住所-->
    <%= current_customer.last_name %><%= current_customer.first_name %>
    <!--名前-->
    <br>

    <%= f.radio_button :select_address, 1 %>
    <%= f.label :select_address_1, "登録済住所から選択" %>
    <br>
    <%= f.select :address_id, options_from_collection_for_select(current_customer.shipping_addresses.all, :id, :address_display) %>
    <br>
    
    <%= f.radio_button :select_address, 2 %>
    <%= f.label :select_address_2, "新しいお届け先" %>
    <br>
    <%= f.label :postal_code, "郵便番号（ハイフンなし）" %>
    <%= f.text_field :postal_code, placeholder:"0000000" %>
    <br>
    <%= f.label :address, "住所" %>
    <%= f.text_field :address, placeholder:"東京都渋谷区代々木神園町0-0", size: "30x30" %>
    <br>
    <%= f.label :address_name, "宛名" %>
    <%= f.text_field :address_name, placeholder:"令和道子" %>
    <br>
    
    <%= f.submit "確認画面へ進む"%>
    
  <% end %>
</div>

app/views/customer/orders/show.html.erb
<div class="container">
    <h2>注文履歴詳細</h2>
    <div class="row">
        <div class="col-lg-7">
            <p>注文情報</p>
            <table class="table table-bordered">
                <tr>
                    <th>注文日</th>
                    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
                </tr>
                <tr>
                    <th>配送先</th>
                    <td>
                        〒<%= @order.postal_code %>
                        <br>
                        <%= @order.address %>
                        <br>
                        <%= @order.address_name %>
                    </td>
                </tr>
                <tr>
                    <th>支払い方法</th>
                    <td><%= @order.payment_method_i18n %></td>
                </tr>
                <tr>
                    <th>ステータス</th>
                    <td><%= @order.status_i18n %></td>
                </tr>
            </table>
        </div>
        <div class="col-lg-5">
            <p>請求情報</p>
            <table class="table table-bordered">
                <tr>
                    <th>商品合計</th>
                    <td><%= @order.payment.to_s(:delimited) %></td>
                </tr>
                <tr>
                    <th>配送料</th>
                    <td><%= @order.postage.to_s(:delimited) %></td>
                </tr>
                <tr>
                    <th>ご請求額</th>
                    <td><%= (@order.payment + @order.postage).to_s(:delimited) %></td>
                </tr>
            </table>
        </div>
        <div>
            <p>注文内容</p>
            <table class="table table-bordered">
                <thead>
                    <th>商品</th>
                    <th>単価（税込）</th>
                    <th>数量</th>
                    <th>小計</th>
                </thead>
                
                <tbody>
                    <% @order.order_details.each do |order_detail| %>
                        <tr>
                            <td><%= order_detail.item.name %></td>
                            <td><%= order_detail.price_def.to_s(:delimited) %></td>
                            <td><%= order_detail.quantity %></td>
                            <td><%= (order_detail.price_def * order_detail.quantity).to_s(:delimited) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>