config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get root to: 'homes#top'
    get 'admin/homes/index/:id',to: 'homes#index'
    resources :items, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    #以下の内容でも
    # resources :customers, only: %i[index show edit update]
  end

  scope module: :customer do
    root to: "homes#top"
    get 'homes/about'
    # resource :customers, only: %i[show edit update] do
    #   collection do
    #     get 'unsubscribe'
    #     patch 'withdrawal'
    #   end
    # end
    get 'customers/unsubscribe', to: 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal', to: 'customers#withdrawal', as: 'withdrawal'
    get 'customers/show', to: 'customers#show'
    get 'customers/edit_information', to: 'customers#edit'
    patch 'customers/update', to: 'customers#update'
    resources :items, only: [:index, :show, :create]
    resources :cart_items, only: %i[index update destroy create] do
      delete 'destroy_all', on: :collection
    end
    resources :shipping_addresses, only: %i[index create edit update destroy]
    resources :orders, only: %i[new index create show] do
      collection do
        get 'check'
        get 'completed'
      end
    end
  end

  resources :genres, only: [:index, :create, :edit, :update ]

end

app/models/order.rb
class Order < ApplicationRecord

  with_options presence: true do
    validates :payment_method
    validates :payment
    validates :postage
    validates :address
    validates :postal_code
    validates :address_name
    validates :status
  end
  
  #購入方法
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  #注文ステータス
  enum status: {
    
    waiting_payment: 0,      #入金待ち
    payment_confirmation: 1, #入金確認
    production: 2,           #製作中
    shipping_preparation: 3, #発送準備中
    sent: 4                  #発送済み
    
  }

  # with_options uniqueness: true do
  # end
  
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  def address_display
  '〒' + postal_code + ' ' + address
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    if order.update(order_params)
      redirect_to admin_order_path(order.id)
      flash[:notice] = "注文商品の更新に成功しました。"
    else
      flash[:notice] = "注文商品の更新に失敗しました。"
      render :show
    end
    
    order.order_details.update(production_status: 1) if order.status == "payment_confirmation"
  end
  
  private
  
  def order_params
    params.require(:order).permit(:customer_id, :payment_method, :payment, :postage, :address, :postal_code, :address_name, :status)
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  before_action :authenticate_customer!
  before_action :set_params, only: %i[show]

  def new
    @order = Order.new
  end

  def check
    @order = Order.new(order_params)
    @cart_items = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }  #商品合計金額の計算
    if params[:order][:select_address] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.address_name = current_customer.last_name + current_customer.first_name

    elsif params[:order][:select_address] == "1"
      @address = ShippingAddress.find(params[:order][:address_id])
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.address_name = @address.address_name
    elsif params[:order][:select_address] == "2"

    else
      @order = Order.new
      render :new
      flash[:notice] = "再度ご確認の上、ご入力してください。"
    end
    @order.postage = 800
  end

  def completed
  end

  def create
    order = current_customer.orders.new(order_params)
    cart_item = current_customer.cart_items.all
    order.status = 0

    if order.save
      cart_item.each do |cart_item| 
        OrderDetail.create(   #注文詳細モデルのカラムのcreate
          item_id: cart_item.item_id, order_id: order.id,
          quantity: cart_item.amount, price: cart_item.item.price
        )
      end
      cart_item.destroy_all
      redirect_to completed_orders_path
    else
      @order = Order.new
      render :new
      flash[:notice] = "注文の確定に失敗しました。"
    end
    
  end

  def index
    @orders = current_customer.orders.all
    # byebug
  end

  def show
    @orders = current_customer.orders.find(params[:id])
    # @order_detail = current_customer.order_details.all
  end

  private


  def set_params
    @order = Order.find(params[:id])
  end

  def order_params
    # params.require(:order).permit(:payment_method, :postal_code, :address, :address_name)
    params.require(:order).permit(:customer_id, :payment_method, :payment, :postage, :address, :postal_code, :address_name, :status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  <div class="row">
    <div class="col-lg-10"> 
      <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
        <table class="table table-borderless">
          <tr>
            <th>購入者</th>
            <td><%= @order.customer.last_name%> <%= @order.customer.first_name %></td>
          </tr>
          <tr>
            <th>注文日</th>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <th>配送先</th>
            <td>
              <%= @order.address_display %>
              <%= @order.address_name %>
            </td>
          </tr>
          <tr>
            <th>支払い方法</th>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <th>注文ステータス</th>
            <td>
              <%= f.select :status, Order.statuses_i18n.invert %>
              <%= f.submit "更新", class: "btn btn-outline-success" %>
            </td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8">
        <table class="table table-bordered">
          <thead>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </thead>
          
          <tbody>
            <% @order.order_details.each do |order| %>
              <%= form_with model: order, url: admin_order_detail_path(order.id), method: :patch do |f| %>
                <tr>
                  <td><%= order.item.name %></td>
                  <td><%= order.price_def.to_s(:delimited) %></td>
                  <td><%= order.quantity %></td>
                  <td><%= order.subtotal.to_s(:delimited) %></td>
                  <td>
                    <%= f.select :production_status, OrderDetail.production_statuses_i18n.invert %>
                    <%= f.submit "更新", class: "btn btn-outline-success" %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
    </div>
    <div class="col-lg-4">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= @order.payment %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= @order.payment + @order.postage %></td>
        </tr>
      </table>
    </div>
  </div>
</div>